# https://taskfile.dev
version: "3"

includes:
  go:
    taskfile: https://raw.githubusercontent.com/flexigpt/.github/refs/heads/main/tasks/go.yml
    checksum: 03c767b893839644d0116ce06a5b35b3c89279d591639bfcd9cc8753136abc38
    flatten: true
    dir: "{{.ROOT_DIR}}"
    vars:
      GREETING: Hello, these are MapStore tasks!
      DEPGRAPH_ENTRY_POINT: store_directory.go
