# https://taskfile.dev
version: "3"

includes:
  go:
    taskfile: https://raw.githubusercontent.com/flexigpt/.github/refs/heads/main/tasks/go.yml
    checksum: a4bb1a41eab7cc097d7224f58b1c31cdfde8b9cc75a4a967488cef26071f9da2
    # Required for remote Taskfiles so commands execute in this repository.
    dir: "{{.ROOT_DIR}}"
    vars:
      GREETING: Hello, these are MapStore tasks!
      DEPGRAPH_ENTRY_POINT: store_directory.go

tasks:
  default:
    cmds:
      - task: go:default
