# https://taskfile.dev
version: "3"

includes:
  go:
    taskfile: https://raw.githubusercontent.com/flexigpt/.github/refs/heads/main/tasks/go.yml
    checksum: 6c5b0575d175fb76291861cd77e646d1cd94bf1008660f331ec9dfe85ca63166
    flatten: true
    dir: "{{.ROOT_DIR}}"
    vars:
      GREETING: Hello, these are MapStore tasks!
      DEPGRAPH_ENTRY_POINT: store_directory.go
