name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go:
    name: Go - test (${{ matrix.os }}, ${{ matrix.go-source }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-2022, macos-15 ]
        go-source: [ minimum, dev ]
        include:
          - go-source: minimum
            go-version-file: go.mod
          - go-source: dev
            go-version-file: .tool-versions

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set-up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ matrix.go-version-file }}
          cache: true

      - name: Unlock keyring
        if: runner.os == 'Linux'
        uses: t1m0thyj/unlock-keyring@v1

      - name: Test with coverage
        if: matrix.os == 'ubuntu-24.04' && matrix.go-source == 'dev'
        run: |
          go test -count=1 -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Check test coverage
        if: matrix.os == 'ubuntu-24.04' && matrix.go-source == 'dev'
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml

      - name: Test
        if: matrix.os != 'ubuntu-24.04' || matrix.go-source != 'dev'
        run: go test ./...
